---
title: "Fall 2022 Galleria field infection data"
author: "Morgan Swoboda"
date: "2023-02-08"
output: github_document
---

# Package install and upload data sheet
```{r, eval = TRUE}

#install.packages("emmeans")
#install.packages("ggthemes")

library(ggplot2)
library(emmeans)
library(tidyr)
library(dplyr)
library(ggthemes)
library(RColorBrewer)

#import data
Fall22EPF <- read.csv("Fall 22 epf bioassay.csv")

#make treatments and varieties into factors
Fall22EPF$treatment = factor(Fall22EPF$treatment, levels = c("Control", "10Met", "10Bb"))
Fall22EPF$variety = factor(Fall22EPF$variety, levels = c("Cochise", "Armani"))
```

#Prelim data check
```{r}
ggplot(data = Fall22EPF, aes(x = treatment, y = perc.inf.total, color = variety)) + geom_boxplot() + ggtitle("Total infection")
#everything looks ok

ggplot(data = Fall22EPF, aes(x = treatment, y = perc.met.total, color = variety)) + geom_boxplot() + ggtitle("Metarhizium infection")
```
# Stats for Metarhizium - normal ANOVA way?
```{r}
attach(Fall22EPF)

##two way ANOVA
two.way.Met <- aov(perc.met.total~treatment*variety)
summary(two.way.Met) #no signifcant differences, no interaction, change to one way model instead
summary.lm(two.way.Met)

##one way anova
one.way.Met <- aov(perc.met.total~treatment)
summary(one.way.Met) #not significant
summary.lm(one.way.Met)
plot(one.way.Met) #probably not normal based on QQ plot, looks like it's exponential?
shapiro.test(resid(one.way.Met)) #residuals NOT normal
fligner.test(perc.met.total~treatment) #normal

# KW instead since it's not normal
##KW for met
MetF22KW <- kruskal.test(perc.met.total~treatment)
print(MetF22KW) #not significant

detach(Fall22EPF)
```


